__lib_pinggy_version = "0.1.6"
__lib_pinggy_url_prefix = "https://github.com/Pinggy-io/libpinggy/releases/download/v"

# `_version.py` is generated by setuptools_scm at build time and is
# gitignored. In a fresh source checkout (no build run yet) the file
# may be missing; fall back to a clearly-bogus version so import works.
try:
    from ._version import version as __version__
except ImportError:
    __version__ = "0.0.0+unknown"
