"""lean business catalog

Revision ID: 0006_lean_business_catalog
Revises: 0005_tenant_store_management
Create Date: 2026-07-28 10:02:39.367539
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '0006_lean_business_catalog'
down_revision: Union[str, Sequence[str], None] = '0005_tenant_store_management'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Set either acknowledgement to True only after explicit review and documentation.
DESTRUCTIVE_MIGRATION_ACKNOWLEDGED = False
EMPTY_DOWNGRADE_ALLOWED = False


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'inactive', 'archived')", name='ck_catalog_attributes_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_catalog_attributes_id_tenant'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_catalog_attributes_tenant_code')
    )
    with op.batch_alter_table('catalog_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_attributes_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_attributes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_attributes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('catalog_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'inactive', 'archived')", name='ck_catalog_brands_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_catalog_brands_id_tenant'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_catalog_brands_tenant_slug')
    )
    with op.batch_alter_table('catalog_brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_brands_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_brands_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_brands_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('catalog_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'inactive', 'archived')", name='ck_catalog_categories_status'),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name='ck_catalog_category_not_self'),
    sa.ForeignKeyConstraint(['parent_id', 'tenant_id'], ['catalog_categories.id', 'catalog_categories.tenant_id'], name='fk_catalog_categories_parent_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_catalog_categories_id_tenant'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_catalog_categories_tenant_slug')
    )
    with op.batch_alter_table('catalog_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_categories_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_categories_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_categories_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_catalog_categories_tenant_parent', ['tenant_id', 'parent_id'], unique=False)

    op.create_table('catalog_media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'ready', 'failed', 'archived')", name='ck_catalog_media_assets_status'),
    sa.CheckConstraint('file_size >= 0', name='ck_catalog_media_assets_file_size'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_catalog_media_assets_id_tenant'),
    sa.UniqueConstraint('tenant_id', 'storage_provider', 'storage_key', name='uq_catalog_media_storage_key')
    )
    with op.batch_alter_table('catalog_media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_media_assets_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_media_assets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_media_assets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('catalog_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'inactive', 'archived')", name='ck_catalog_tags_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_catalog_tags_id_tenant'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_catalog_tags_tenant_slug')
    )
    with op.batch_alter_table('catalog_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_tags_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_tags_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_tags_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('catalog_attribute_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('normalized_value', sa.String(length=200), nullable=False),
    sa.Column('display_label', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'inactive', 'archived')", name='ck_catalog_attribute_options_status'),
    sa.ForeignKeyConstraint(['attribute_id', 'tenant_id'], ['catalog_attributes.id', 'catalog_attributes.tenant_id'], name='fk_catalog_attribute_options_attribute_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_id', 'normalized_value', name='uq_catalog_attribute_option_value'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_catalog_attribute_options_id_tenant')
    )
    with op.batch_alter_table('catalog_attribute_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_attribute_options_attribute_id'), ['attribute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_attribute_options_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_attribute_options_status'), ['status'], unique=False)
        batch_op.create_index('ix_catalog_attribute_options_tenant_attribute', ['tenant_id', 'attribute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_attribute_options_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('catalog_brand_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id', 'tenant_id'], ['catalog_brands.id', 'catalog_brands.tenant_id'], name='fk_catalog_brand_media_brand_tenant'),
    sa.ForeignKeyConstraint(['media_asset_id', 'tenant_id'], ['catalog_media_assets.id', 'catalog_media_assets.tenant_id'], name='fk_catalog_brand_media_asset_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'media_asset_id', 'role', name='uq_catalog_brand_media')
    )
    with op.batch_alter_table('catalog_brand_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_brand_media_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_brand_media_media_asset_id'), ['media_asset_id'], unique=False)
        batch_op.create_index(
            'ix_catalog_brand_media_one_primary',
            ['brand_id', 'role'],
            unique=True,
            postgresql_where=sa.text('is_primary'),
            sqlite_where=sa.text('is_primary = 1'),
        )
        batch_op.create_index(batch_op.f('ix_catalog_brand_media_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('catalog_category_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id', 'tenant_id'], ['catalog_categories.id', 'catalog_categories.tenant_id'], name='fk_catalog_category_media_category_tenant'),
    sa.ForeignKeyConstraint(['media_asset_id', 'tenant_id'], ['catalog_media_assets.id', 'catalog_media_assets.tenant_id'], name='fk_catalog_category_media_asset_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'media_asset_id', 'role', name='uq_catalog_category_media')
    )
    with op.batch_alter_table('catalog_category_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_category_media_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_category_media_media_asset_id'), ['media_asset_id'], unique=False)
        batch_op.create_index(
            'ix_catalog_category_media_one_primary',
            ['category_id', 'role'],
            unique=True,
            postgresql_where=sa.text('is_primary'),
            sqlite_where=sa.text('is_primary = 1'),
        )
        batch_op.create_index(batch_op.f('ix_catalog_category_media_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('catalog_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("product_type IN ('physical', 'digital', 'service')", name='ck_catalog_offerings_product_type'),
    sa.CheckConstraint("status IN ('draft', 'active', 'inactive', 'archived')", name='ck_catalog_offerings_status'),
    sa.ForeignKeyConstraint(['brand_id', 'tenant_id'], ['catalog_brands.id', 'catalog_brands.tenant_id'], name='fk_catalog_offerings_brand_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_catalog_offerings_id_tenant'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_catalog_offerings_tenant_slug')
    )
    with op.batch_alter_table('catalog_offerings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_offerings_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_offerings_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_offerings_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_offerings_status'), ['status'], unique=False)
        batch_op.create_index('ix_catalog_offerings_tenant_brand', ['tenant_id', 'brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_offerings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_catalog_offerings_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index('ix_catalog_offerings_tenant_type', ['tenant_id', 'product_type'], unique=False)

    op.create_table('catalog_product_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_variant_defining', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id', 'tenant_id'], ['catalog_attributes.id', 'catalog_attributes.tenant_id'], name='fk_catalog_product_attributes_attribute_tenant'),
    sa.ForeignKeyConstraint(['product_id', 'tenant_id'], ['catalog_offerings.id', 'catalog_offerings.tenant_id'], name='fk_catalog_product_attributes_product_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'attribute_id', name='uq_catalog_product_attribute')
    )
    with op.batch_alter_table('catalog_product_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_product_attributes_attribute_id'), ['attribute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_product_attributes_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_product_attributes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_catalog_product_attributes_tenant_product', ['tenant_id', 'product_id'], unique=False)

    op.create_table('catalog_product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id', 'tenant_id'], ['catalog_categories.id', 'catalog_categories.tenant_id'], name='fk_catalog_product_categories_category_tenant'),
    sa.ForeignKeyConstraint(['product_id', 'tenant_id'], ['catalog_offerings.id', 'catalog_offerings.tenant_id'], name='fk_catalog_product_categories_product_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'category_id', name='uq_catalog_product_category')
    )
    with op.batch_alter_table('catalog_product_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_product_categories_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_product_categories_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_product_categories_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_catalog_product_categories_tenant_product', ['tenant_id', 'product_id'], unique=False)

    op.create_table('catalog_product_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id', 'tenant_id'], ['catalog_media_assets.id', 'catalog_media_assets.tenant_id'], name='fk_catalog_product_media_asset_tenant'),
    sa.ForeignKeyConstraint(['product_id', 'tenant_id'], ['catalog_offerings.id', 'catalog_offerings.tenant_id'], name='fk_catalog_product_media_product_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'media_asset_id', 'role', name='uq_catalog_product_media')
    )
    with op.batch_alter_table('catalog_product_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_product_media_media_asset_id'), ['media_asset_id'], unique=False)
        batch_op.create_index(
            'ix_catalog_product_media_one_primary',
            ['product_id', 'role'],
            unique=True,
            postgresql_where=sa.text('is_primary'),
            sqlite_where=sa.text('is_primary = 1'),
        )
        batch_op.create_index(batch_op.f('ix_catalog_product_media_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_product_media_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('catalog_product_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id', 'tenant_id'], ['catalog_offerings.id', 'catalog_offerings.tenant_id'], name='fk_catalog_product_tags_product_tenant'),
    sa.ForeignKeyConstraint(['tag_id', 'tenant_id'], ['catalog_tags.id', 'catalog_tags.tenant_id'], name='fk_catalog_product_tags_tag_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'tag_id', name='uq_catalog_product_tag')
    )
    with op.batch_alter_table('catalog_product_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_product_tags_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_product_tags_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_product_tags_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_catalog_product_tags_tenant_product', ['tenant_id', 'product_id'], unique=False)

    op.create_table('catalog_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('combination_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'inactive', 'archived')", name='ck_catalog_variants_status'),
    sa.ForeignKeyConstraint(['product_id', 'tenant_id'], ['catalog_offerings.id', 'catalog_offerings.tenant_id'], name='fk_catalog_variants_product_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_catalog_variants_id_tenant'),
    sa.UniqueConstraint('product_id', 'combination_key', name='uq_catalog_variant_combination')
    )
    with op.batch_alter_table('catalog_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_variants_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_variants_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_variants_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_variants_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_catalog_variants_tenant_product', ['tenant_id', 'product_id'], unique=False)

    op.create_table('catalog_skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'inactive', 'archived')", name='ck_catalog_skus_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['variant_id', 'tenant_id'], ['catalog_variants.id', 'catalog_variants.tenant_id'], name='fk_catalog_skus_variant_tenant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_catalog_skus_id_tenant'),
    sa.UniqueConstraint('tenant_id', 'barcode', name='uq_catalog_skus_tenant_barcode'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_catalog_skus_tenant_code')
    )
    with op.batch_alter_table('catalog_skus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_skus_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_skus_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_skus_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_skus_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_skus_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_catalog_skus_tenant_variant', ['tenant_id', 'variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_skus_variant_id'), ['variant_id'], unique=False)

    op.create_table('catalog_variant_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id', 'tenant_id'], ['catalog_media_assets.id', 'catalog_media_assets.tenant_id'], name='fk_catalog_variant_media_asset_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['variant_id', 'tenant_id'], ['catalog_variants.id', 'catalog_variants.tenant_id'], name='fk_catalog_variant_media_variant_tenant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'media_asset_id', 'role', name='uq_catalog_variant_media')
    )
    with op.batch_alter_table('catalog_variant_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_variant_media_media_asset_id'), ['media_asset_id'], unique=False)
        batch_op.create_index(
            'ix_catalog_variant_media_one_primary',
            ['variant_id', 'role'],
            unique=True,
            postgresql_where=sa.text('is_primary'),
            sqlite_where=sa.text('is_primary = 1'),
        )
        batch_op.create_index(batch_op.f('ix_catalog_variant_media_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_variant_media_variant_id'), ['variant_id'], unique=False)

    op.create_table('catalog_variant_option_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('attribute_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id', 'tenant_id'], ['catalog_attributes.id', 'catalog_attributes.tenant_id'], name='fk_catalog_variant_options_attribute_tenant'),
    sa.ForeignKeyConstraint(['attribute_option_id', 'tenant_id'], ['catalog_attribute_options.id', 'catalog_attribute_options.tenant_id'], name='fk_catalog_variant_options_option_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['variant_id', 'tenant_id'], ['catalog_variants.id', 'catalog_variants.tenant_id'], name='fk_catalog_variant_options_variant_tenant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'attribute_id', name='uq_catalog_variant_attribute'),
    sa.UniqueConstraint('variant_id', 'attribute_option_id', name='uq_catalog_variant_option')
    )
    with op.batch_alter_table('catalog_variant_option_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_variant_option_values_attribute_id'), ['attribute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_variant_option_values_attribute_option_id'), ['attribute_option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_variant_option_values_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_variant_option_values_variant_id'), ['variant_id'], unique=False)
        batch_op.create_index('ix_catalog_variant_options_tenant_variant', ['tenant_id', 'variant_id'], unique=False)

    op.create_table('catalog_sku_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id', 'tenant_id'], ['catalog_media_assets.id', 'catalog_media_assets.tenant_id'], name='fk_catalog_sku_media_asset_tenant'),
    sa.ForeignKeyConstraint(['sku_id', 'tenant_id'], ['catalog_skus.id', 'catalog_skus.tenant_id'], name='fk_catalog_sku_media_sku_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'media_asset_id', 'role', name='uq_catalog_sku_media')
    )
    with op.batch_alter_table('catalog_sku_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_sku_media_media_asset_id'), ['media_asset_id'], unique=False)
        batch_op.create_index(
            'ix_catalog_sku_media_one_primary',
            ['sku_id', 'role'],
            unique=True,
            postgresql_where=sa.text('is_primary'),
            sqlite_where=sa.text('is_primary = 1'),
        )
        batch_op.create_index(batch_op.f('ix_catalog_sku_media_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_sku_media_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('catalog_store_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("NOT (quantity = 0 AND availability_status = 'in_stock')", name='ck_catalog_store_availability_zero'),
    sa.CheckConstraint("availability_status IN ('in_stock', 'low_stock', 'out_of_stock', 'preorder', 'unavailable')", name='ck_catalog_store_availability_status'),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 0', name='ck_catalog_store_availability_quantity'),
    sa.ForeignKeyConstraint(['sku_id', 'tenant_id'], ['catalog_skus.id', 'catalog_skus.tenant_id'], name='fk_catalog_store_availability_sku_tenant'),
    sa.ForeignKeyConstraint(['store_id', 'tenant_id'], ['stores.id', 'stores.tenant_id'], name='fk_catalog_store_availability_store_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku_id', name='uq_catalog_store_availability')
    )
    with op.batch_alter_table('catalog_store_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_store_availability_availability_status'), ['availability_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_store_availability_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_store_availability_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_store_availability_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_store_availability_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_catalog_store_availability_tenant_sku', ['tenant_id', 'sku_id'], unique=False)
        batch_op.create_index('ix_catalog_store_availability_tenant_store', ['tenant_id', 'store_id'], unique=False)

    op.create_table('catalog_store_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('compare_at_price IS NULL OR compare_at_price >= price', name='ck_catalog_store_prices_compare'),
    sa.CheckConstraint('price >= 0', name='ck_catalog_store_prices_price'),
    sa.ForeignKeyConstraint(['sku_id', 'tenant_id'], ['catalog_skus.id', 'catalog_skus.tenant_id'], name='fk_catalog_store_prices_sku_tenant'),
    sa.ForeignKeyConstraint(['store_id', 'tenant_id'], ['stores.id', 'stores.tenant_id'], name='fk_catalog_store_prices_store_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku_id', 'currency', name='uq_catalog_store_price')
    )
    with op.batch_alter_table('catalog_store_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_store_prices_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_store_prices_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_store_prices_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_store_prices_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_store_prices_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_catalog_store_prices_tenant_sku', ['tenant_id', 'sku_id'], unique=False)
        batch_op.create_index('ix_catalog_store_prices_tenant_store', ['tenant_id', 'store_id'], unique=False)

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_stores_id_tenant', ['id', 'tenant_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_stores_id_tenant', type_='unique')

    with op.batch_alter_table('catalog_store_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_store_prices_tenant_store')
        batch_op.drop_index('ix_catalog_store_prices_tenant_sku')
        batch_op.drop_index(batch_op.f('ix_catalog_store_prices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_store_prices_store_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_store_prices_sku_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_store_prices_public_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_store_prices_is_active'))

    op.drop_table('catalog_store_prices')
    with op.batch_alter_table('catalog_store_availability', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_store_availability_tenant_store')
        batch_op.drop_index('ix_catalog_store_availability_tenant_sku')
        batch_op.drop_index(batch_op.f('ix_catalog_store_availability_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_store_availability_store_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_store_availability_sku_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_store_availability_public_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_store_availability_availability_status'))

    op.drop_table('catalog_store_availability')
    with op.batch_alter_table('catalog_sku_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_sku_media_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_sku_media_sku_id'))
        batch_op.drop_index(
            'ix_catalog_sku_media_one_primary',
            postgresql_where=sa.text('is_primary'),
            sqlite_where=sa.text('is_primary = 1'),
        )
        batch_op.drop_index(batch_op.f('ix_catalog_sku_media_media_asset_id'))

    op.drop_table('catalog_sku_media')
    with op.batch_alter_table('catalog_variant_option_values', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_variant_options_tenant_variant')
        batch_op.drop_index(batch_op.f('ix_catalog_variant_option_values_variant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_variant_option_values_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_variant_option_values_attribute_option_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_variant_option_values_attribute_id'))

    op.drop_table('catalog_variant_option_values')
    with op.batch_alter_table('catalog_variant_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_variant_media_variant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_variant_media_tenant_id'))
        batch_op.drop_index(
            'ix_catalog_variant_media_one_primary',
            postgresql_where=sa.text('is_primary'),
            sqlite_where=sa.text('is_primary = 1'),
        )
        batch_op.drop_index(batch_op.f('ix_catalog_variant_media_media_asset_id'))

    op.drop_table('catalog_variant_media')
    with op.batch_alter_table('catalog_skus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_skus_variant_id'))
        batch_op.drop_index('ix_catalog_skus_tenant_variant')
        batch_op.drop_index(batch_op.f('ix_catalog_skus_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_skus_status'))
        batch_op.drop_index(batch_op.f('ix_catalog_skus_public_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_skus_code'))
        batch_op.drop_index(batch_op.f('ix_catalog_skus_barcode'))

    op.drop_table('catalog_skus')
    with op.batch_alter_table('catalog_variants', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_variants_tenant_product')
        batch_op.drop_index(batch_op.f('ix_catalog_variants_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_variants_status'))
        batch_op.drop_index(batch_op.f('ix_catalog_variants_public_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_variants_product_id'))

    op.drop_table('catalog_variants')
    with op.batch_alter_table('catalog_product_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_product_tags_tenant_product')
        batch_op.drop_index(batch_op.f('ix_catalog_product_tags_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_product_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_product_tags_product_id'))

    op.drop_table('catalog_product_tags')
    with op.batch_alter_table('catalog_product_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_product_media_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_product_media_product_id'))
        batch_op.drop_index(
            'ix_catalog_product_media_one_primary',
            postgresql_where=sa.text('is_primary'),
            sqlite_where=sa.text('is_primary = 1'),
        )
        batch_op.drop_index(batch_op.f('ix_catalog_product_media_media_asset_id'))

    op.drop_table('catalog_product_media')
    with op.batch_alter_table('catalog_product_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_product_categories_tenant_product')
        batch_op.drop_index(batch_op.f('ix_catalog_product_categories_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_product_categories_product_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_product_categories_category_id'))

    op.drop_table('catalog_product_categories')
    with op.batch_alter_table('catalog_product_attributes', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_product_attributes_tenant_product')
        batch_op.drop_index(batch_op.f('ix_catalog_product_attributes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_product_attributes_product_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_product_attributes_attribute_id'))

    op.drop_table('catalog_product_attributes')
    with op.batch_alter_table('catalog_offerings', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_offerings_tenant_type')
        batch_op.drop_index('ix_catalog_offerings_tenant_status')
        batch_op.drop_index(batch_op.f('ix_catalog_offerings_tenant_id'))
        batch_op.drop_index('ix_catalog_offerings_tenant_brand')
        batch_op.drop_index(batch_op.f('ix_catalog_offerings_status'))
        batch_op.drop_index(batch_op.f('ix_catalog_offerings_public_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_offerings_name'))
        batch_op.drop_index(batch_op.f('ix_catalog_offerings_brand_id'))

    op.drop_table('catalog_offerings')
    with op.batch_alter_table('catalog_category_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_category_media_tenant_id'))
        batch_op.drop_index(
            'ix_catalog_category_media_one_primary',
            postgresql_where=sa.text('is_primary'),
            sqlite_where=sa.text('is_primary = 1'),
        )
        batch_op.drop_index(batch_op.f('ix_catalog_category_media_media_asset_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_category_media_category_id'))

    op.drop_table('catalog_category_media')
    with op.batch_alter_table('catalog_brand_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_brand_media_tenant_id'))
        batch_op.drop_index(
            'ix_catalog_brand_media_one_primary',
            postgresql_where=sa.text('is_primary'),
            sqlite_where=sa.text('is_primary = 1'),
        )
        batch_op.drop_index(batch_op.f('ix_catalog_brand_media_media_asset_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_brand_media_brand_id'))

    op.drop_table('catalog_brand_media')
    with op.batch_alter_table('catalog_attribute_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_attribute_options_tenant_id'))
        batch_op.drop_index('ix_catalog_attribute_options_tenant_attribute')
        batch_op.drop_index(batch_op.f('ix_catalog_attribute_options_status'))
        batch_op.drop_index(batch_op.f('ix_catalog_attribute_options_public_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_attribute_options_attribute_id'))

    op.drop_table('catalog_attribute_options')
    with op.batch_alter_table('catalog_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_tags_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_tags_status'))
        batch_op.drop_index(batch_op.f('ix_catalog_tags_public_id'))

    op.drop_table('catalog_tags')
    with op.batch_alter_table('catalog_media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_media_assets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_media_assets_status'))
        batch_op.drop_index(batch_op.f('ix_catalog_media_assets_public_id'))

    op.drop_table('catalog_media_assets')
    with op.batch_alter_table('catalog_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_categories_tenant_parent')
        batch_op.drop_index(batch_op.f('ix_catalog_categories_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_categories_status'))
        batch_op.drop_index(batch_op.f('ix_catalog_categories_public_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_categories_parent_id'))

    op.drop_table('catalog_categories')
    with op.batch_alter_table('catalog_brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_brands_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_brands_status'))
        batch_op.drop_index(batch_op.f('ix_catalog_brands_public_id'))

    op.drop_table('catalog_brands')
    with op.batch_alter_table('catalog_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_attributes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_attributes_status'))
        batch_op.drop_index(batch_op.f('ix_catalog_attributes_public_id'))

    op.drop_table('catalog_attributes')
    # ### end Alembic commands ###
